AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role para EC2 con acceso a S3 y SSM

Resources:
  RDSBackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  RDSBackupInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RDSBackupRole
      Path: /

Outputs:
  InstanceProfile:
    Value: !Ref RDSBackupInstanceProfile
